Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,27 +40,26 @@ jobs:
           dockerfile: dev/docker/Dockerfile
           buildoptions: "--compress"
 
-  deploy:
+  deploy-demo:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - uses: chrnorm/deployment-action@releases/v1
-        name: Create GitHub deployment for ${GITHUB_REF##*/}
-        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
+        if: github.ref == 'refs/heads/master'
+        name: Create GitHub deployment for demo
         id: deployment
         with:
           token: "${{ github.token }}"
-          target_url: https://${GITHUB_REF##*/}.europe-west1.gcp.storefrontcloud.io
+          target_url: https://demo.europe-west1.gcp.storefrontcloud.io
           environment: production
           initial_status: in_progress
-
-      # Deploy on test/demo depending on the branch that triggered the workflow
-      - name: Deploy on ${GITHUB_REF##*/}.europe-west1.gcp.storefrontcloud.io
-        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
+      # Deploy on demo    
+      - name: Deploy on demo.europe-west1.gcp.storefrontcloud.io
+        if: github.ref == 'refs/heads/master' 
         run: |
-          if curl -s -H 'X-User-Id: ${{ secrets.CLOUD_USERNAME }}'  -H 'X-Api-Key: ${{ secrets.CLOUD_PASSWORD }}' -H 'Content-Type: application/json' -X POST -d '
+          if curl -s -u ${{ secrets.DEPLOYMENT_USER }}:${{ secrets.DEPLOYMENT_PASSWORD }} -H 'Content-Type: application/json' -X POST -d '
           {
-              "code":"${GITHUB_REF##*/}",
+              "code":"demo",
               "region":"europe-west1.gcp",
               "frontContainerVersion":"${{ github.sha }}"
           }' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
@@ -70,21 +69,73 @@ jobs:
             exit 1
           fi
 
+      # Return status
       - name: Update deployment status (success)
-        if: success() && github.ref == 'refs/heads/master' || success() && github.ref == 'refs/heads/develop'
+        if: success() 
         uses: chrnorm/deployment-status@releases/v1
         with:
           token: "${{ github.token }}"
-          target_url: https://${GITHUB_REF##*/}.europe-west1.gcp.storefrontcloud.io
+          target_url: https://demo.europe-west1.gcp.storefrontcloud.io
           state: "success"
           description: Congratulations! The deploy is done.
           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
+
       - name: Update deployment status (failure)
-        if: failure() && github.ref == 'refs/heads/master' || failure() && github.ref == 'refs/heads/develop'
+        if: failure()  
         uses: chrnorm/deployment-status@releases/v1
         with:
           token: "${{ github.token }}"
-          target_url: https://${GITHUB_REF##*/}.europe-west1-southeast1.gcp.storefrontcloud.io
+          target_url: https://demo.europe-west1-southeast1.gcp.storefrontcloud.io
+          description: Unfortunately, the instance hasn't been updated.
+          state: "failure"
+          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
+
+  deploy-test:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: chrnorm/deployment-action@releases/v1
+        if: github.ref == 'refs/heads/develop' 
+        name: Create GitHub deployment for test
+        id: deployment
+        with:
+          token: "${{ github.token }}"
+          target_url: https://test.europe-west1.gcp.storefrontcloud.io
+          environment: production
+          initial_status: in_progress
+      # Deploy on demo    
+      - name: Deploy on test.europe-west1.gcp.storefrontcloud.io
+        if: github.ref == 'refs/heads/develop' 
+        run: |
+          if curl -s -u ${{ secrets.DEPLOYMENT_USER }}:${{ secrets.DEPLOYMENT_PASSWORD }} -H 'Content-Type: application/json' -X POST -d '
+          {
+              "code":"test",
+              "region":"europe-west1.gcp",
+              "frontContainerVersion":"${{ github.sha }}"
+          }' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
+            echo "Instance updated"
+          else
+            echo "Something went wrong during the update process..."
+            exit 1
+          fi
+
+      # Return status
+      - name: Update deployment status (success)
+        if: success() 
+        uses: chrnorm/deployment-status@releases/v1
+        with:
+          token: "${{ github.token }}"
+          target_url: https://test.europe-west1.gcp.storefrontcloud.io
+          state: "success"
+          description: Congratulations! The deploy is done.
+          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
+
+      - name: Update deployment status (failure)
+        if: failure()  
+        uses: chrnorm/deployment-status@releases/v1
+        with:
+          token: "${{ github.token }}"
+          target_url: https://test.europe-west1-southeast1.gcp.storefrontcloud.io
           description: Unfortunately, the instance hasn't been updated.
           state: "failure"
           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
